### ISSUE TITLE
I would like to know if this project cannot run on the x86_64 architecture？

### ISSUE THREAD

**Issue by wwwxLin** [rtenlab/reference-system-paam#2]
When I was running this command‘colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebInfo -DPICAS=TRUE -DPAAM=TRUE --packages-select paam_server’, the following error occurred.

make[3]: warning: -j12 forced in submake: resetting jobserver mode.
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a(interpreter.o): Relocations in generic ELF (EM: 183)
/usr/bin/ld: libtensorflow-lite.a: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/paam_server.dir/build.make:315: paam_server] Error 1
make[1]: *** [CMakeFiles/Makefile2:256: CMakeFiles/paam_server.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
---
Failed   <<< paam_server [1min 21s, exited with code 2]

I would like to know if compiling TensorFlow by myself or replacing the error-causing file with an x86 architecture version of libtensorflow-lite.a, would allow the project to run?

**Comment by Denri006** [comment]
Yes it works with x86 and discrete nvgpu. use the CMakeLists_x86.txt for this

**Comment by wwwxLin** [comment]
Thank you very much for your reply



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2024年10月12日(星期六) 上午8:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [rtenlab/reference-system-paam] I would like to know if this project cannot run on the x86_64 architecture？ (Issue #2)














 
Yes it works with x86 and discrete nvgpu. use the CMakeLists_x86.txt for this
